### ISSUE TITLE
Failed to lookup symbol 'RSABridgeCall': dlsym(RTLD_DEFAULT, RSABridgeCall): symbol not found

### ISSUE THREAD

**Issue by FlutterEngineers** [jerson/flutter-rsa#91]
On Android, the latest Flutter plugin version (fast_rsa: ^3.8.5) works correctly.
On iOS, the app runs fine in release mode on a local device, but after uploading to TestFlight, it encounters the issue described above.

After researching, I found that the latest plugin version uses native iOS fast_rsa 0.7.0, which causes the problem. The app works correctly if the native iOS fast_rsa is forced to version 0.6.0.

**Comment by jerson** [comment]
Hi we have released a new version using force load to prevent stripping on release/profile https://pub.dev/packages/fast_rsa/versions/3.8.6

**Comment by zahidrehmanicloud-art** [comment]
I’m still facing the same issue on iOS even after upgrading to the latest version of the fast_rsa plugin (v3.8.6).
The issue does not occur on Android, and the app works perfectly fine in both debug and release modes locally.
However, once the app is uploaded to TestFlight, it fails to function as expected.

Environment Details

Device: iPhone 13 Pro

Platform: iOS

iOS Version:  iOS 26

Flutter Version: Latest Stable release

fast_rsa Version: 3.8.6

Xcode Version 26.0.1

Build Mode: Works fine locally in Release mode, but fails in TestFlight/Production mode.

**Comment by dustinkerstein** [comment]
I also am seeing the same error in TestFlight builds on version 3.8.6

**Comment by HQ-2019** [comment]
> Hi we have released a new version using force load to prevent stripping on release/profile https://pub.dev/packages/fast_rsa/versions/3.8.6

I also am seeing the same error in TestFlight builds on version 3.8.6

**Comment by zjoart** [comment]
is there any solution to this

**Comment by zjoart** [comment]
it is not fixed yet on 3.8.6 @jerson

**Comment by nedngotass** [comment]
3.8.6 have same issue

**Comment by servetozden** [comment]
similar problem

**Comment by swapabhi** [comment]
Same issue in 8.3.6
Any updates on the solution?

**Comment by mzeeshan-whizpool** [comment]
facing same issue in 3.8.6

**Comment by Tolulope05** [comment]
what is the solution? Who has gotten any solution

**Comment by ragavendranbala-TSL** [comment]
I'm facing the same issue

**Comment by hensi-elaunch** [comment]
I'm facing the same issue

**Comment by dustinkerstein** [comment]
See https://github.com/jerson/flutter-rsa/issues/85#issuecomment-5349135021 for a potential workaround

**Comment by FlutterEngineers** [comment]
please use  this   https://pub.dev/packages/fortis
